name: Deploy landing page to S3
on:
  push:
    branches:
      - main

jobs:
  deploy-landing-page:
    name: Deploy landing page to S3
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 🎵 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🧶 Install Yarn
        run: npm --global install yarn

      - name: 📦 Install packages
        run: yarn install
        working-directory: landingpage

      - name: 👷‍♂️ Build and bundle
        run: yarn build
        working-directory: landingpage

      - name: 📂 Upload files
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'bravoapps-landing-page'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist'

      - name: ⏳ Invalidate CloudFront cache
        uses: awact/cloudfront-action@master
        env:
          SOURCE_DIR: '/'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION_ID: ${{ secrets.AWS_LANDING_PAGE_DISTRIBUTION_ID }}
